# Generated by Django 6.0.3 on 2026-04-07 18:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=core.models.default_question_options, help_text='Варианты ответов, например: ["да", "нет"]'),
        ),
    ]
