# Generated by Django 6.0.3 on 2026-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audiofile_deleted_at_audiofile_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientquizassignment',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Когда тест перестаёт быть доступен. null = бессрочно.', null=True, verbose_name='Крайний срок'),
        ),
        migrations.AddField(
            model_name='patientquizassignment',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Когда тест становится доступен. null = сразу.', null=True, verbose_name='Начало доступа'),
        ),
    ]
