# Generated by Django 6.0.3 on 2026-04-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientquizassignment_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='starting_sound',
            field=models.ForeignKey(blank=True, help_text='Звук, воспроизводимый перед каждым тестом пациента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_sound_patients', to='core.audiofile', verbose_name='Стартовый звук'),
        ),
        migrations.CreateModel(
            name='AudioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.audiocategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория аудио',
                'verbose_name_plural': 'Категории аудио',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='audiofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_files', to='core.audiocategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('patient_transferred', 'Пациент передан'), ('patient_added', 'Пациент добавлен'), ('quiz_completed', 'Тест пройден')], max_length=30, verbose_name='Тип')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
