# Generated by Django 6.0.3 on 2026-04-15 07:26

from django.db import migrations


def populate_default_category(apps, schema_editor):
    AudioCategory = apps.get_model('core', 'AudioCategory')
    AudioFile = apps.get_model('core', 'AudioFile')
    default_cat, _ = AudioCategory.objects.get_or_create(name='Общая', parent=None)
    AudioFile.objects.filter(category__isnull=True).update(category=default_cat)


def reverse_default_category(apps, schema_editor):
    AudioFile = apps.get_model('core', 'AudioFile')
    AudioFile.objects.all().update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audio_categories_notifications_starting_sound'),
    ]

    operations = [
        migrations.RunPython(populate_default_category, reverse_default_category),
    ]
