# Generated by Django 6.0.3 on 2026-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patient_options_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='logging_enabled',
            field=models.BooleanField(default=False, help_text='Если включено, все пациенты этого врача отправляют клиентские логи на сервер', verbose_name='Логирование клиента'),
        ),
        migrations.AddField(
            model_name='patient',
            name='logging_enabled',
            field=models.BooleanField(default=False, help_text='Если включено, приложение пациента отправляет логи всех запросов на сервер', verbose_name='Логирование клиента'),
        ),
    ]
