# Generated by Django 6.0.3 on 2026-06-22 19:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_logging_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_token_expiry),
        ),
    ]
