# Generated by Django 6.0.3 on 2026-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientquizassignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Когда врач впервые открыл результат. null = не просмотрен.', null=True, verbose_name='Просмотрено врачом'),
        ),
    ]
