# Generated by Django 6.0.3 on 2026-07-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_patientquizassignment_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50, verbose_name='Версия')),
                ('version_code', models.PositiveIntegerField(verbose_name='Номер сборки')),
                ('apk', models.FileField(upload_to='releases/', verbose_name='APK')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер, байт')),
                ('commit_sha', models.CharField(blank=True, max_length=40, verbose_name='Git commit')),
                ('notes', models.TextField(blank=True, verbose_name='Описание релиза')),
                ('is_default', models.BooleanField(default=False, verbose_name='Дефолтный релиз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Собран')),
            ],
            options={
                'verbose_name': 'Релиз APK',
                'verbose_name_plural': 'Релизы APK',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('version_name', 'version_code'), name='uniq_release_version'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_release')],
            },
        ),
    ]
