# Generated by Django 6.0.3 on 2026-07-10 07:33

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CLINIC_NAME = 'Клиника №1'
DEFAULT_CLINIC_ABBR = 'CLN'


def create_default_clinic(apps, schema_editor):
    """Создать дефолтную клинику и привязать к ней всех существующих пациентов."""
    Clinic = apps.get_model('core', 'Clinic')
    Patient = apps.get_model('core', 'Patient')
    clinic, _ = Clinic.objects.get_or_create(
        abbreviation=DEFAULT_CLINIC_ABBR,
        defaults={'name': DEFAULT_CLINIC_NAME},
    )
    Patient.objects.filter(clinic__isnull=True).update(clinic=clinic)


def noop_reverse(apps, schema_editor):
    """Откат: FK обнулится вместе с удалением поля, отдельных действий не нужно."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('abbreviation', models.CharField(help_text='Короткая латинская аббревиатура (по типу аэропортов), например MSK. Используется как префикс логина пациента.', max_length=10, unique=True, verbose_name='Аббревиатура')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.clinic', verbose_name='Клиника'),
        ),
        migrations.RunPython(create_default_clinic, noop_reverse),
    ]
