# Generated by Django 6.0.3 on 2026-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clinic_patient_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(choices=[('да', 'Слышу'), ('нет', 'Не слышу')], default='да', max_length=255),
        ),
    ]
